# Generated by Django 4.2 on 2023-04-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_alter_member_balance_transaction_pooltable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pooltable",
            old_name="total_paused_time",
            new_name="usage_time",
        ),
    ]
