# Generated by Django 4.2 on 2023-04-27 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_rename_total_paused_time_pooltable_usage_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="pooltable",
            name="total_paused_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
