# Generated by Django 4.2 on 2023-04-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0005_pooltable_total_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="pooltable",
            name="price_per_minute",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
